# Bing Web Search API settings
BING_SEARCH_V7_SUBSCRIPTION_KEY = "YOUR_KEY_HERE"
BING_SEARCH_V7_ENDPOINT = "https://api.bing.microsoft.com"

# OpenAI API settings
OPENAI_API_KEY = "YOUR_KEY_HERE"
OPENAI_MAX_RETRY_COUNT = 3
LANGUAGE_MODEL = "gpt-4"
